### ISSUE TITLE
Have the user input their mood for that day and save that data to the user

### ISSUE THREAD

**Issue by gasawase** [HennyBicks01/MoodCalendar#3]

**Comment by gasawase** [comment]
Have them pick some buttons "Bad", "Neutral", and "Good". This can be updated to images later.

**Comment by gasawase** [comment]
Have them be able to write down their symptoms or a summary of their day.

**Comment by gasawase** [comment]
Display the date at the top

**Comment by h-nny** [comment]
Summer achieved this by creating a friendly new mood page which pops up based on the date chosen
