### ISSUE TITLE
show moods on a calendar format

### ISSUE THREAD

**Issue by gasawase** [HennyBicks01/MoodCalendar#5]
Change the color of the day based on the mood. When creating the calendar, have it look through the database and see if the dates already have a mood color and update the square for it.

**Comment by gasawase** [comment]
WANT TO DO IF TIME: have dates from past and future months be greyed out, make buttons and fonts prettier,

**Comment by h-nny** [comment]
created a Get mood color function shown here:
`public static Color GetMoodColor(DateTime date)
        {
            // If the date is in the future, return gray
            if (date.Date > DateTime.Now.Date)
            {
                return Color.FromHex("#D3D3D3"); // Gray color
            }
            Tuple<string, string> dateStatus;
            if (DateStatus.TryGetValue(date, out dateStatus))
            {
                switch (dateStatus.Item1) // Mood is the first item in the tuple
                {
                    case "Good":
                        return Color.FromHex("#98FB98");
                    case "Neutral":
                        return Color.FromHex("#FDFD96");
                    case "Bad":
                        return Color.FromHex("#FF6961");
                    default:
                        return Color.White; // Default color
                }
            }
            else
            {
                return Color.White; // Default color for dates without a mood
            }
        }`

**Comment by h-nny** [comment]
this code changes the background of the calendar button based on the mood selected for that day and grays out any future dates since another function i made makes them unacessable
